CREATE TABLE activities (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(255) NOT NULL,
  duration VARCHAR(255) NOT NULL,
  difficulty VARCHAR(50) NOT NULL,
  bestTime VARCHAR(255) NOT NULL,
  imageUrl VARCHAR(255) NOT NULL,
  icon VARCHAR(50) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
